# Generated by Django 3.2 on 2021-04-30 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200424_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section')),
            ],
        ),
        migrations.CreateModel(
            name='Subheading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('recipe', models.TextField()),
                ('heading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.heading')),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='section',
        ),
        migrations.DeleteModel(
            name='Subtopic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
