# Generated by Django 3.2.1 on 2021-05-05 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200424_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subheading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('recipe', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Topic',
            new_name='Heading',
        ),
        migrations.DeleteModel(
            name='Subtopic',
        ),
        migrations.AddField(
            model_name='subheading',
            name='heading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.heading'),
        ),
    ]
